### ISSUE TITLE
invalid vendor path?

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-filter-useragent#22]
this construct https://github.com/colinsurprenant/logstash-filter-useragent/blob/2c1429f9ba95d2aaf903543e192014e299dee068/lib/logstash/filters/useragent.rb#L65 is wrong and `LogStash::Environment::vendor_path` should be used. 

The current `path = ::File.expand_path('../../../vendor/regexes.yaml', ::File.dirname(__FILE__))` will look in a `vendor/` dir relative to this plugin installation path which might not be in the same location as the logstash installation.

**Comment by colinsurprenant** [comment]
also there is no spec for this.

**Comment by kares** [comment]
closing - no longer relevant
