### ISSUE TITLE
useragent filter plugin in logstash 

### ISSUE THREAD

**Issue by MohammedEsameel** [logstash-plugins/logstash-filter-useragent#52]
- Version: logstash 6.0
- Operating System: centos 7
- Config File : 
input {
    beats {
        port => "5000"
        type => "nginx"

}

   beats {
        port => "5044"
        type => "haproxy"
}

}

filter {

   grok {
                match => { "message" => "%{HAPROXYHTTP}" 
               match => { "message" => ["%{IPORHOST:[nginx][access][remote_ip]} - %{DATA:[nginx][access]
                                [user_name]} \[%{HTTPDATE:[nginx][access][time]}\] \"%{WORD:[nginx][access]
                                [method]} %{DATA:[nginx][access][url]} HTTP/%{NUMBER:[nginx][access]
                                [http_version]}\" %{NUMBER:[nginx][access][response_code]} %{NUMBER:[nginx]
                                [access][body_sent][bytes]} \"%{DATA:[nginx][access][referrer]}\" \"%{DATA:[nginx]
                                [access][agent]}\""] 
        }

}

output {

 if [type] == "haproxy" {
    elasticsearch {
    hosts => [ "10.1.12.109:9200" ]
      index => "haproxy_test-index"
    }

>>>>>>>>>>>>>>>
the result is in the image below that is get all info about the access log and did not detect a specific user agent or browser name or device name !
>> 
![image](https://user-images.githubusercontent.com/32281761/33982646-449d3962-e0c2-11e7-9ccf-89232f47fc73.png)

>>
i have 2 indexes , one for nginx access log and the second is for the haproxy log , 
so please i want to get the device name , useragent , OS type of the requester typed in kibana as individual fields .
Please help .

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.

Looking at your configuration, you aren't using this useragent filter at all, you must add
`useragent { source => "[nginx][access][remote_ip]" }` at the bottom of your filter section
