### ISSUE TITLE
Useragent filter plugin reports false IE version

### ISSUE THREAD

**Issue by larryhe** [logstash-plugins/logstash-filter-useragent#53]
On our Kibana browser report, a lot of IE11 reported as IE7 which is very confusing to our whole engineering team. for example, given below user agent string ```Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)```, which is actually IE11, but it shows as IE7.0 on Kibana report. 

We should use a similar algorithm to [ie-truth](https://github.com/Gavin-Paolucci-Kleinow/ie-truth/blob/master/ie-truth.js) to calculate real IE version.

**Comment by larryhe** [comment]
Hi @yaauie thanks for your quick response. So when can we get the fix in?

**Comment by yaauie** [comment]
The updated lookup file has been released with version 3.2.3 of this plugin.

Please check the [Updating Plugins docs](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#updating-plugins) to find update steps.
