### ISSUE TITLE
Implement ECS-Compatibility Mode

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-filter-useragent#66]
As a part of the effort to make plugins able to run in an ECS-Compatible manner
by default in an upcoming release of Logstash, this plugin needs to implement
an ECS-Compatibility mode that does not implicitly use fields that conflict
with ECS.

Absent `target` directive, this plugin populates a number of root-level fields
which are _undefined_ in ECS  and therefore has the possiblity of conflicting
with future versions of ECS. The plugin may benefit from an ECS-Compatibility
mode that requires the target to be set explicitly, by using the ECS-compatible
root-level `user_agent` object as a default target, or otherwise reduces the
risk of future conflict.

Additionally, the sub-fields in ECS-Compatibility mode should be normalized to
the [ECS User Agent object type](https://www.elastic.co/guide/en/ecs/current/ecs-user_agent.html).

**Comment by kares** [comment]
Nested user agent fields will likely need to be adjusted for ECS
 - `user_agent.name`, `user_agent.os.family`, etc.

Also, should default `source` be `'user_agent.original'` in ECS mode ?

**Comment by yaauie** [comment]
Currently the `source` needs to be explicitly given, but adding a sensible ECS-Compatible default could improve usability, especially if we end up placing raw user-agent strings in this location due to ECS-Compatibility modes of other plugins.

**Comment by nithril** [comment]
+1, currently this plugin cannot be used in substitution of the Elastic user_agent processor.

**Comment by kares** [comment]
ECS support shipped in https://github.com/logstash-plugins/logstash-filter-useragent/pull/68
