### ISSUE TITLE
plugin never uses vendor/regexes.yaml since uap gem already includes it

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-filter-useragent#7]
```
% find . -name regexes.yaml
./vendor/bundle/jruby/1.9/gems/logstash-filter-useragent-1.0.1/vendor/regexes.yaml
./vendor/bundle/jruby/1.9/gems/user_agent_parser-2.2.0/vendor/ua-parser/regexes.yaml
```

Deleting the first yaml file doesn't stop it from working, only deleting the second one, included in the ua-parser gem.

It seems the first file is only loaded if [UserAgentParser::Parser.new raises an exception](https://github.com/logstash-plugins/logstash-filter-useragent/blob/master/lib/logstash/filters/useragent.rb#L42-L47), which doesn't happen

**Comment by kares** [comment]
closing as defunct issue
