### ISSUE TITLE
regexes.yaml repository changed, logstash plugin uses old version of file

### ISSUE THREAD

**Issue by maximpashuk** [logstash-plugins/logstash-filter-useragent#9]
Documentation (https://www.elastic.co/guide/en/logstash/master/plugins-filters-useragent.html#plugins-filters-useragent-regexes) says that regexes.yaml used from repository https://github.com/tobie/ua-parser

https://github.com/tobie/ua-parser repository is oldone
newone is https://github.com/ua-parser/uap-core

regexes.yaml that bundled in logstash 1.5.2 I am using now is outdated, so I used to explicitly set "regexes" property.

Please change reference to repository that hold regexes.yaml file, so file bundled in logstash will be newest.

**Comment by mmuszkow** [comment]
+1
The regexes.yaml file shipped with logstash-filter-useragent doesn't handle the new OS X/iOS versions and Edge browser correctly. Time for update.
